### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by calebcartwright** [badges/squint#2]
I'm assuming there's no reason we'd want a different CoC for this repo, and that Contributor Covenant would be the way to go. 

We could either add the file in-repo similar to https://github.com/badges/shields/pull/5236 in the main repo, though I suppose we could also consider leveraging [default community health files](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) for the badges org to apply across all repos?

**Comment by paulmelnikow** [comment]
Ooh, I didn't know about default community health files! That's cool! We could start with funding.yml which is already in place. We're still finalizing the contacts for badges/shields#5236 but we could add that in soon after.

**Comment by calebcartwright** [comment]
I'm going to go ahead and add our same CoC files from shields to this repo. I'd rather get it in sooner rather than later, especially with the cutover, and we'll always have the ability to remove the in-file CoC file if/when we setup a community health repo and files.

**Comment by chris48s** [comment]
Straying a bit off topic here, but..

Your .github repo can now also include a README.md for the organisation too https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/ which is cool.

One thing we do need to be slightly mindful of if we start using a .github repo is impact on other projects under the badges org (really just poser tbh - I think it is the only active non-shields project). For example, if we put a funding.yml in a .github repo, I think that then automatically makes the funding CTA for all repos that are already created under the badges org without its own funding.yml "give money to shields.io". In the case of funding.yml specifically, poser actually have their own funding CTA already https://github.com/badges/poser/blob/master/.github/FUNDING.yml which would override the default but we need to consider the fact that `@badges !== shields.io` sometimes.

**Comment by paulmelnikow** [comment]
Agree with that… might be another reason to spin off projects that aren't part of shields.io.

**Comment by chris48s** [comment]
> might be another reason to spin off projects that aren't part of shields.io

I wonder if the path of least resistance would actually be to transfer the active shields.io projects:

- https://github.com/badges/shields
- https://github.com/badges/squint
- https://github.com/badges/daily-tests
- https://github.com/badges/shields-ops

to a new org e.g: https://github.com/shields_io and all of the core/ops team can be allowed to create repos under the new org, etc.

The advantage of doing it that way round is we could _just do it_

**Comment by paulmelnikow** [comment]
Hmm, interesting…

**Comment by calebcartwright** [comment]
Sorry, forgot I'd used the close keyword. Think it's probably worth revisiting the org-level pieces in a separate/focused thread anyway, maybe a topic for next ops meeting?

**Comment by chris48s** [comment]
Yes for sure :+1:  I did note in the first post I was going a bit off-topic
