### ISSUE TITLE
improve emoji rendering

### ISSUE THREAD

**Issue by chris48s** [badges/squint#7]
Making a note of this here as it came up on discord.
The current raster server doesn't e.g:
https://img.shields.io/badge/yes-%F0%9F%91%8D-blue.svg
https://raster.shields.io/badge/yes-%F0%9F%91%8D-blue.png
I've not tested squint.

**Comment by calebcartwright** [comment]
Checking now (need to get the review app for https://github.com/badges/shields/pull/5754 deployed again), but I'll be pleasantly surprised if it works

**Comment by chris48s** [comment]
So emoji rendering is a mixed bag. Some of them work totally fine. e.g:

- https://squint-test.herokuapp.com/badge/emoji-%E2%9D%A4%EF%B8%8F-blue.svg
- https://squint-test.herokuapp.com/badge/emoji-%F0%9F%98%8E-blue.svg
- https://squint-test.herokuapp.com/badge/emoji-%F0%9F%98%80-blue.svg

..and some of them not only don't render the emoji character, but also completely ruin everything else on the badge:

- https://squint-test.herokuapp.com/badge/emoji-%F0%9F%91%8D-blue.svg
- https://squint-test.herokuapp.com/badge/emoji-%F0%9F%87%B3%F0%9F%87%B4-blue.svg
- https://squint-test.herokuapp.com/badge/emoji-%F0%9F%90%8F-blue.svg

**Comment by calebcartwright** [comment]
I'm actually pleasantly surprised that _any_ of them are working. I wonder if we need to grab some additional packages (fonts or otherwise) in order to improve things here
